const works=[
['watercolor-architecture.png','Свет и масса','акварельная архитектура','Главное — вертикали здания и диагональ дороги.','конструктивный каркас','Сделайте три миниатюры: массы, оси, один акцент.'],
['0045.webp','Маршрут и большие массы','линейный этюд','Главное — направление пространства и крупная вертикаль.','пропорции','Уберите детали и оставьте три формы.'],
['watercolor-nature.png','Воздух и ритм','акварельный пейзаж','Главное — дерево, небо и светлая пауза слева.','планы и свет','Сведите сцену к трём планам.'],
['0235.webp','Деревья и глубина','наблюдение','Главное — перекрытия переднего и дальнего плана.','глубина','Нарисуйте только три уровня контраста.'],
['0066.webp','Вода как поле','тональный этюд','Главное — большое спокойное поле отражения.','тональные массы','Перерисуйте пятью значениями тона.'],
['0088.webp','Ритм листьев','наблюдение','Главное — общий силуэт, а не перечень листьев.','иерархия деталей','Сделайте силуэт, пять листьев и три детали.'],
['0108.webp','Лист как форма','конструкция','Главное — ось и плоскость органической формы.','простая геометрия','Проведите ось, плоскость и контур.'],
['0170.webp','Велосипед и перспектива','конструкция','Главное — ось движения и два эллипса колёс.','пропорции','Постройте предмет из осей и эллипсов.'],
['0214.webp','Фасад как блок','архитектура','Главное — вертикали и ритм окон.','массы и интервалы','Соберите фасад из трёх пятен.'],
['watercolor-city.png','Городской центр','акварельная архитектура','Главное — красная плоскость и большое светлое поле.','активная пустота','Сравните плотную и свободную кадрировку.'],
['0244.webp','Городской угол','композиция','Главное — точка зрения и треугольник улицы.','перспективный ритм','Оставьте не более десяти линий.'],
['0248.webp','Материальная деталь','фактура','Главное — контраст поверхности и пустого поля.','материальность','Сделайте чёрно-белый квадрат фактуры.']
];
const rooms=[['Наблюдение','Увидеть силуэт, ритм, тон и выбрать детали.',0,1],['Воздух','Собрать пейзаж из планов, света и пауз.',2,3],['Вода','Свести отражение и поверхность к тональным массам.',4,5],['Конструкция','Построить органическую форму и предмет из осей.',6,7],['Архитектура','Прочитать фасад и город как систему масс.',8,9],['Композиция','Собрать точку зрения, пустоту и материальный акцент.',10,11]];
let roomIndex=0,drag=false,lastX=0,rotation=0;const $=s=>document.querySelector(s), views=['welcome','route','tour','catalog','finish'];
function show(id){views.forEach(v=>$('#'+v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:'smooth'})}
function renderRoute(){ $('#routeGrid').innerHTML=rooms.map((r,i)=>`<button class="route-card" data-room="${i}"><small>ЗАЛ ${String(i+1).padStart(2,'0')} / 06</small><strong>${r[0]}</strong><span>${r[1]}</span></button>`).join('');document.querySelectorAll('.route-card').forEach(b=>b.onclick=()=>{roomIndex=+b.dataset.room;renderRoom();show('tour')})}
function renderRoom(){const r=rooms[roomIndex];$('#roomNumber').textContent=`ЗАЛ ${String(roomIndex+1).padStart(2,'0')} / 06`;$('#roomTitle').textContent=r[0];$('#roomText').textContent=r[1];$('#progressText').textContent=`${String(roomIndex+1).padStart(2,'0')} / 06`;$('#progressBar').style.width=`${(roomIndex+1)/6*100}%`;const pair=[works[r[2]],works[r[3]]];$('#sceneWorks').innerHTML=pair.map((w,i)=>`<button class="scene-work w${i}" data-work="${r[i+2]}"><img src="assets/${w[0]}" alt="${w[1]}"><b>${w[1]}</b></button>`).join('');document.querySelectorAll('.scene-work').forEach(b=>b.onclick=()=>openWork(+b.dataset.work));rotation=[0,14,-10,8,-16,5][roomIndex];$('#camera').style.transform=`rotateY(${rotation}deg)`;$('#prev').disabled=roomIndex===0;$('#next').textContent=roomIndex===rooms.length-1?'Завершить →':'Далее →'}
function renderCatalog(){ $('#catalogGrid').innerHTML=works.map((w,i)=>`<button class="work-card" data-work="${i}"><img src="assets/${w[0]}" alt="${w[1]}"><div><small>${w[2]}</small><h3>${w[1]}</h3><p>${w[3]}</p></div></button>`).join('');document.querySelectorAll('.work-card').forEach(b=>b.onclick=()=>openWork(+b.dataset.work))}
function openWork(i){const w=works[i];$('#modalInner').innerHTML=`<div class="modal-card"><img src="assets/${w[0]}" alt="${w[1]}"><div class="modal-copy"><small class="overline">ЭКСПОНАТ ${String(i+1).padStart(2,'0')} · РАЗВЁРТКА</small><h2>${w[1]}</h2><p><b>Наблюдение.</b> ${w[3]}</p><p><b>Развиваемый навык.</b> ${w[4]}.</p><div class="task"><b>Учебное задание</b><p>${w[5]}</p></div><p>Сначала сформулируйте главное одним предложением. Затем сделайте быстрый вариант без попытки объяснить каждую деталь.</p></div></div>`;$('#modal').classList.add('open')}
$('#start').onclick=()=>{$('#splash').classList.add('off');show('welcome')};$('#beginTour').onclick=()=>{roomIndex=0;renderRoom();show('tour')};$('#mapBtn').onclick=()=>show('route');$('#catalogBtn').onclick=()=>show('catalog');$('#resetBtn').onclick=()=>{roomIndex=0;rotation=0;$('#splash').classList.remove('off');show('welcome')};$('#prev').onclick=()=>{if(roomIndex>0){roomIndex--;renderRoom()}};$('#next').onclick=()=>{if(roomIndex<rooms.length-1){roomIndex++;renderRoom()}else show('finish')};$('#finishMap').onclick=()=>show('route');$('#finishCatalog').onclick=()=>show('catalog');$('#close').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal').classList.remove('open');if(e.key==='ArrowRight'&&!$('#tour').classList.contains('hidden'))$('#next').click();if(e.key==='ArrowLeft'&&!$('#tour').classList.contains('hidden'))$('#prev').click()});
$('#scene').addEventListener('pointerdown',e=>{if(e.target.closest('.scene-work'))return;drag=true;lastX=e.clientX;$('#scene').setPointerCapture(e.pointerId)});$('#scene').addEventListener('pointermove',e=>{if(!drag)return;rotation+=(e.clientX-lastX)*.25;lastX=e.clientX;$('#camera').style.transform=`rotateY(${rotation}deg)`});['pointerup','pointercancel'].forEach(x=>$('#scene').addEventListener(x,()=>drag=false));$('#scene').addEventListener('wheel',e=>{e.preventDefault();rotation+=e.deltaY*.04;$('#camera').style.transform=`rotateY(${rotation}deg)`},{passive:false});renderRoute();renderCatalog();renderRoom();
